name: persepolis
version: 3.2.0
summary: Persepolis
description: |
  Persepolis is a download manager & a GUI for Aria2.
base: core18

icon: resources/persepolis.svg
grade: stable
confinement: strict

apps:
  persepolis:
    command: bin/persepolis
    command-chain: [bin/desktop-launch]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all

  persepolis:
    build-snaps: &snaps
      - ffmpeg/latest/stable
      - youtube-dl/latest/stable
    stage-snaps: *snaps
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - aria2
      - pulseaudio-utils
      - sound-theme-freedesktop
    stage-packages:
      - aria2
      - libnotify-bin
      - pulseaudio-utils
      - python-six
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - python3-requests
      - python3-setproctitle
      - python3-psutil
      - sound-theme-freedesktop 
